// Generated by gencpp from file assignment_2_2022/ReachedResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2022_MESSAGE_REACHEDRESPONSE_H
#define ASSIGNMENT_2_2022_MESSAGE_REACHEDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_2_2022
{
template <class ContainerAllocator>
struct ReachedResponse_
{
  typedef ReachedResponse_<ContainerAllocator> Type;

  ReachedResponse_()
    : reached(0)
    , cancelled(0)  {
    }
  ReachedResponse_(const ContainerAllocator& _alloc)
    : reached(0)
    , cancelled(0)  {
  (void)_alloc;
    }



   typedef int32_t _reached_type;
  _reached_type reached;

   typedef int32_t _cancelled_type;
  _cancelled_type cancelled;





  typedef boost::shared_ptr< ::assignment_2_2022::ReachedResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_2_2022::ReachedResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReachedResponse_

typedef ::assignment_2_2022::ReachedResponse_<std::allocator<void> > ReachedResponse;

typedef boost::shared_ptr< ::assignment_2_2022::ReachedResponse > ReachedResponsePtr;
typedef boost::shared_ptr< ::assignment_2_2022::ReachedResponse const> ReachedResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_2_2022::ReachedResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_2_2022::ReachedResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_2_2022::ReachedResponse_<ContainerAllocator1> & lhs, const ::assignment_2_2022::ReachedResponse_<ContainerAllocator2> & rhs)
{
  return lhs.reached == rhs.reached &&
    lhs.cancelled == rhs.cancelled;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_2_2022::ReachedResponse_<ContainerAllocator1> & lhs, const ::assignment_2_2022::ReachedResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_2_2022

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2022::ReachedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2022::ReachedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2022::ReachedResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2022::ReachedResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2022::ReachedResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2022::ReachedResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_2_2022::ReachedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d21c4923e63883c429d739eacdfb354d";
  }

  static const char* value(const ::assignment_2_2022::ReachedResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd21c4923e63883c4ULL;
  static const uint64_t static_value2 = 0x29d739eacdfb354dULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_2_2022::ReachedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_2_2022/ReachedResponse";
  }

  static const char* value(const ::assignment_2_2022::ReachedResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_2_2022::ReachedResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 reached\n"
"int32 cancelled\n"
"\n"
;
  }

  static const char* value(const ::assignment_2_2022::ReachedResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_2_2022::ReachedResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.reached);
      stream.next(m.cancelled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReachedResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_2_2022::ReachedResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_2_2022::ReachedResponse_<ContainerAllocator>& v)
  {
    s << indent << "reached: ";
    Printer<int32_t>::stream(s, indent + "  ", v.reached);
    s << indent << "cancelled: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cancelled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_2_2022_MESSAGE_REACHEDRESPONSE_H
