// Generated by gencpp from file assignment_2_2022/Reached.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2022_MESSAGE_REACHED_H
#define ASSIGNMENT_2_2022_MESSAGE_REACHED_H

#include <ros/service_traits.h>


#include <assignment_2_2022/ReachedRequest.h>
#include <assignment_2_2022/ReachedResponse.h>


namespace assignment_2_2022
{

struct Reached
{

typedef ReachedRequest Request;
typedef ReachedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Reached
} // namespace assignment_2_2022


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_2_2022::Reached > {
  static const char* value()
  {
    return "d21c4923e63883c429d739eacdfb354d";
  }

  static const char* value(const ::assignment_2_2022::Reached&) { return value(); }
};

template<>
struct DataType< ::assignment_2_2022::Reached > {
  static const char* value()
  {
    return "assignment_2_2022/Reached";
  }

  static const char* value(const ::assignment_2_2022::Reached&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_2_2022::ReachedRequest> should match
// service_traits::MD5Sum< ::assignment_2_2022::Reached >
template<>
struct MD5Sum< ::assignment_2_2022::ReachedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2022::Reached >::value();
  }
  static const char* value(const ::assignment_2_2022::ReachedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2022::ReachedRequest> should match
// service_traits::DataType< ::assignment_2_2022::Reached >
template<>
struct DataType< ::assignment_2_2022::ReachedRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2022::Reached >::value();
  }
  static const char* value(const ::assignment_2_2022::ReachedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_2_2022::ReachedResponse> should match
// service_traits::MD5Sum< ::assignment_2_2022::Reached >
template<>
struct MD5Sum< ::assignment_2_2022::ReachedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2022::Reached >::value();
  }
  static const char* value(const ::assignment_2_2022::ReachedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2022::ReachedResponse> should match
// service_traits::DataType< ::assignment_2_2022::Reached >
template<>
struct DataType< ::assignment_2_2022::ReachedResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2022::Reached >::value();
  }
  static const char* value(const ::assignment_2_2022::ReachedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_2_2022_MESSAGE_REACHED_H
