// Generated by gencpp from file my_rosplan_interface/Marker.msg
// DO NOT EDIT!


#ifndef MY_ROSPLAN_INTERFACE_MESSAGE_MARKER_H
#define MY_ROSPLAN_INTERFACE_MESSAGE_MARKER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace my_rosplan_interface
{
template <class ContainerAllocator>
struct Marker_
{
  typedef Marker_<ContainerAllocator> Type;

  Marker_()
    : id(0)
    , corners()  {
    }
  Marker_(const ContainerAllocator& _alloc)
    : id(0)
    , corners(_alloc)  {
  (void)_alloc;
    }



   typedef int64_t _id_type;
  _id_type id;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _corners_type;
  _corners_type corners;





  typedef boost::shared_ptr< ::my_rosplan_interface::Marker_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_rosplan_interface::Marker_<ContainerAllocator> const> ConstPtr;

}; // struct Marker_

typedef ::my_rosplan_interface::Marker_<std::allocator<void> > Marker;

typedef boost::shared_ptr< ::my_rosplan_interface::Marker > MarkerPtr;
typedef boost::shared_ptr< ::my_rosplan_interface::Marker const> MarkerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_rosplan_interface::Marker_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_rosplan_interface::Marker_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_rosplan_interface::Marker_<ContainerAllocator1> & lhs, const ::my_rosplan_interface::Marker_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.corners == rhs.corners;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_rosplan_interface::Marker_<ContainerAllocator1> & lhs, const ::my_rosplan_interface::Marker_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_rosplan_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_rosplan_interface::Marker_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_rosplan_interface::Marker_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_rosplan_interface::Marker_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_rosplan_interface::Marker_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_rosplan_interface::Marker_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_rosplan_interface::Marker_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_rosplan_interface::Marker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "29e916ca9398fbd7b2424ca3f887845d";
  }

  static const char* value(const ::my_rosplan_interface::Marker_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x29e916ca9398fbd7ULL;
  static const uint64_t static_value2 = 0xb2424ca3f887845dULL;
};

template<class ContainerAllocator>
struct DataType< ::my_rosplan_interface::Marker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_rosplan_interface/Marker";
  }

  static const char* value(const ::my_rosplan_interface::Marker_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_rosplan_interface::Marker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 id\n"
"geometry_msgs/Point[] corners\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::my_rosplan_interface::Marker_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_rosplan_interface::Marker_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.corners);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Marker_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_rosplan_interface::Marker_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_rosplan_interface::Marker_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.id);
    s << indent << "corners[]" << std::endl;
    for (size_t i = 0; i < v.corners.size(); ++i)
    {
      s << indent << "  corners[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.corners[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROSPLAN_INTERFACE_MESSAGE_MARKER_H
